### PR TITLE
Allows to set the version of a dependency

### PR DESCRIPTION
**Pull request by cvgaviao**
Allow to set the version of the dependency

### CODE REVIEW

**Comment by cvgaviao** [comment]
anyone could take a look in this PR, please?

**Comment by ifedorenko** [comment]
I can't merge this unless you sign http://takari.io/support/TakariCLA.pdf.

**Comment by cvgaviao** [comment]
would be better to post a link of a editable CLA doc

**Comment by ifedorenko** [comment]
Fixed by 4c0e6c9

**Pull request closed without merging**
